apiVersion: v1
kind: Service
metadata:
  name: {{ include "banco-app.fullname" . }}-backend
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
    {{- include "banco-app.selectorLabels.backend" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "banco-app.selectorLabels.backend" . | nindent 4 }}
