apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banco-app.fullname" . }}-backend
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
    {{- include "banco-app.selectorLabels.backend" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "banco-app.selectorLabels.backend" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "banco-app.labels" . | nindent 8 }}
        {{- include "banco-app.selectorLabels.backend" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "banco-app.fullname" . }}-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "banco-app.fullname" . }}-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "banco-app.fullname" . }}-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "banco-app.fullname" . }}-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "banco-app.fullname" . }}-config
                  key: DB_PORT
            - name: RUN_SEED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "banco-app.fullname" . }}-config
                  key: RUN_SEED
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
