apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "banco-app.fullname" . }}-config
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "banco-app.fullname" . }}-postgres
  DB_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  PORT: {{ .Values.backend.port | quote }}
  RUN_SEED: {{ .Values.backend.runSeed | quote }}
