apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banco-app.fullname" . }}-frontend
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
    {{- include "banco-app.selectorLabels.frontend" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "banco-app.selectorLabels.frontend" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "banco-app.labels" . | nindent 8 }}
        {{- include "banco-app.selectorLabels.frontend" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
