{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "banco-app.fullname" . }}-ingress
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # API requests go to backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "banco-app.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
          # Everything else goes to frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "banco-app.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
