apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "banco-app.fullname" . }}-postgres
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
    {{- include "banco-app.selectorLabels.postgres" . | nindent 4 }}
spec:
  serviceName: {{ include "banco-app.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "banco-app.selectorLabels.postgres" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "banco-app.labels" . | nindent 8 }}
        {{- include "banco-app.selectorLabels.postgres" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "banco-app.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "banco-app.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "banco-app.fullname" . }}-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.postgres.storage.className }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
