apiVersion: v1
kind: Service
metadata:
  name: {{ include "banco-app.fullname" . }}-postgres
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
    {{- include "banco-app.selectorLabels.postgres" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "banco-app.selectorLabels.postgres" . | nindent 4 }}
