apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banco-app.fullname" . }}-secret
  labels:
    {{- include "banco-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | b64enc }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:%d/%s?schema=public" .Values.postgres.credentials.user .Values.postgres.credentials.password (include "banco-app.fullname" .) (.Values.postgres.port | int) .Values.postgres.credentials.database | b64enc }}
